language: python
python:
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

# services
services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres
# command to run tests
script:
  - python manage.py test
  - coverage run --include=app/* manage.py test

after_success: coveralls
